FROM python:3.6

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common \
        curl \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add - \
    && add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
           $(lsb_release -cs) \
           stable" \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        docker-ce \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV INSTALL_DIRECTORY=/tmp/thrifty
RUN mkdir "${INSTALL_DIRECTORY}"
WORKDIR "${INSTALL_DIRECTORY}"

RUN pip --disable-pip-version-check install -U coverage

ADD test_requirements.txt .
RUN pip --disable-pip-version-check install -U -r test_requirements.txt

ADD requirements.txt .
RUN pip --disable-pip-version-check install -U -r requirements.txt

ADD consul_requirements.txt .
RUN pip --disable-pip-version-check install -U -r consul_requirements.txt

ENV MOUNT_DIRECTORY=/thrifty
WORKDIR "${MOUNT_DIRECTORY}"
ENV PYTHONPATH="${MOUNT_DIRECTORY}"

VOLUME ["${MOUNT_DIRECTORY}", "/var/run/docker.sock"]

CMD ["./run-tests.sh"]
